[package]
name = "echor"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.14"
predicates = "3.1.0"
pretty_assertions = "1.4.0"
